site_name: PHIS
#theme: bootstrap
extra_css:
   - "css/bootstrap.css"
   - "css/site.css"
   - "css/navbar.less"
pages:
   - Home: index.md
   - Experimental Organization: experimental-organization.md
   - Data: datamenu.md
   - Community: community.md
   - Tools: tools.md
   - Events: events.md
   - Object Tracking: object-tracking-example.md
   - Ontologies: ontologies.md
   - EMPHASIS: emphasis_ontologie.md
   - About: about.md