site_name: PHIS
#theme: bootstrap
extra_css:
   - "css/bootstrap.css"
   - "css/site.css"
   - "css/navbar.less"
extra_javascript:
    - "js/bootsrap.js"
    - "js/bootsrap.min.js"
    - "js/npm.js"
pages:
   - Home: index.md
   - User Guide:
        - Experimental Organization: experimental-organization.md
        - Community: community.md
        - Data: datamenu.md
        - Events: events.md
        - Object Tracking: object-tracking-example.md
        - Tools: tools.md
   - Ontologies: ontologies.md
   - About: about.md

