site_name: PHIS
#theme: bootstrap
extra_css:
   - "css/bootstrap.css"
   - "css/site.css"
   - "css/navbar.less"
pages:
   - Home: index.md
   - Experimental Organization: experimental-organization.md
   - Data: Data.md
   - Community: community.md
   - Tools: Tools.md
