site_name: PHIS
site_url: http://www.mkdocs.org
site_description: PHIS documentation with Markdown.
site_author: PHIS Team
#theme: bootstrap
extra_css:
   - "css/bootstrap.css"
   - "css/site.css"
   - "css/navbar.less"
extra_javascript:
    - "js/bootsrap.js"
    - "js/bootsrap.min.js"
    - "js/npm.js"
mdFiles: docs/*/*.md
pages:
   - Home: index.md
   - User Guide:
        - Experimental Organization: experimental-organization.md
        - Community: community.md
        - Data: datamenu.md
        - Events: events.md
        - Object Tracking: object-tracking-example.md
        - Tools: tools.md
   - Ontologies: ontologies.md
   - About: about.md